[2024-06-27T02:36:59.433+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2024-06-27T02:36:59.517+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2024-06-27T02:36:59.543+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T02:36:59.639+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_use.get_urls_task manual__2024-06-27T02:36:56.743301+00:00 [queued]>
[2024-06-27T02:36:59.656+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_use.get_urls_task manual__2024-06-27T02:36:56.743301+00:00 [queued]>
[2024-06-27T02:36:59.658+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-27T02:36:59.695+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_urls_task> on 2024-06-27 02:36:56.743301+00:00
[2024-06-27T02:36:59.718+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1945) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-27T02:36:59.722+0000] {standard_task_runner.py:63} INFO - Started process 1946 to run task
[2024-06-27T02:36:59.717+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'test_use', 'get_urls_task', 'manual__2024-06-27T02:36:56.743301+00:00', '--job-id', '568', '--raw', '--subdir', 'DAGS_FOLDER/first_out.py', '--cfg-path', '/tmp/tmpil24kqje']
[2024-06-27T02:36:59.729+0000] {standard_task_runner.py:91} INFO - Job 568: Subtask get_urls_task
[2024-06-27T02:36:59.860+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2024-06-27T02:36:59.900+0000] {task_command.py:426} INFO - Running <TaskInstance: test_use.get_urls_task manual__2024-06-27T02:36:56.743301+00:00 [running]> on host ccfa35e0da07
[2024-06-27T02:36:59.901+0000] {settings.py:363} DEBUG - Disposing DB connection pool (PID 1946)
[2024-06-27T02:36:59.903+0000] {settings.py:250} DEBUG - Setting up DB connection pool (PID 1946)
[2024-06-27T02:36:59.904+0000] {settings.py:298} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-06-27T02:37:00.078+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2024-06-27T02:37:00.331+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_use' AIRFLOW_CTX_TASK_ID='get_urls_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T02:36:56.743301+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-27T02:36:56.743301+00:00'
[2024-06-27T02:37:00.335+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T02:37:18.161+0000] {fun_user.py:87} INFO - Found id: 00013963483849,
[2024-06-27T02:37:18.413+0000] {python.py:237} INFO - Done. Returned value was: 00013963483849,
[2024-06-27T02:37:18.414+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T02:37:19.109+0000] {taskinstance.py:584} DEBUG - Clearing next_method and next_kwargs.
[2024-06-27T02:37:19.115+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=test_use, task_id=get_urls_task, run_id=manual__2024-06-27T02:36:56.743301+00:00, execution_date=20240627T023656, start_date=20240627T023659, end_date=20240627T023719
[2024-06-27T02:37:19.117+0000] {taskinstance.py:562} DEBUG - Task Duration set to 19.475317
[2024-06-27T02:37:19.234+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T02:37:19.279+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T02:37:19.283+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
