[2024-06-26T07:20:36.294+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2024-06-26T07:20:36.365+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2024-06-26T07:20:36.389+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-26T07:20:36.436+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: PAGE1.process_link_0 manual__2024-06-26T07:20:29.160351+00:00 [queued]>
[2024-06-26T07:20:36.453+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: PAGE1.process_link_0 manual__2024-06-26T07:20:29.160351+00:00 [queued]>
[2024-06-26T07:20:36.455+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-26T07:20:36.493+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_link_0> on 2024-06-26 07:20:29.160351+00:00
[2024-06-26T07:20:36.505+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1504) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-26T07:20:36.511+0000] {standard_task_runner.py:63} INFO - Started process 1505 to run task
[2024-06-26T07:20:36.511+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'PAGE1', 'process_link_0', 'manual__2024-06-26T07:20:29.160351+00:00', '--job-id', '526', '--raw', '--subdir', 'DAGS_FOLDER/page_***.py', '--cfg-path', '/tmp/tmpcew0tb9b']
[2024-06-26T07:20:36.515+0000] {standard_task_runner.py:91} INFO - Job 526: Subtask process_link_0
[2024-06-26T07:20:36.641+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2024-06-26T07:20:36.654+0000] {task_command.py:426} INFO - Running <TaskInstance: PAGE1.process_link_0 manual__2024-06-26T07:20:29.160351+00:00 [running]> on host ccfa35e0da07
[2024-06-26T07:20:36.655+0000] {settings.py:363} DEBUG - Disposing DB connection pool (PID 1505)
[2024-06-26T07:20:36.657+0000] {settings.py:250} DEBUG - Setting up DB connection pool (PID 1505)
[2024-06-26T07:20:36.659+0000] {settings.py:298} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-06-26T07:20:36.855+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2024-06-26T07:20:36.997+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='PAGE1' AIRFLOW_CTX_TASK_ID='process_link_0' AIRFLOW_CTX_EXECUTION_DATE='2024-06-26T07:20:29.160351+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-26T07:20:29.160351+00:00'
[2024-06-26T07:20:36.999+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-26T07:20:38.650+0000] {connectionpool.py:244} DEBUG - Starting new HTTP connection (1): localhost:51561
[2024-06-26T07:20:39.876+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session HTTP/1.1" 200 0
[2024-06-26T07:20:40.760+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/url HTTP/1.1" 200 0
[2024-06-26T07:20:40.791+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/element HTTP/1.1" 200 0
[2024-06-26T07:20:40.825+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "GET /session/f2094bc7b0d0951fb3e816ef9ed97482/element/f.BCC00DE3CA51A86ADAAF72288542F68A.d.0CB3700FB122529312D6F4634E3109EA.e.2/text HTTP/1.1" 200 0
[2024-06-26T07:20:40.827+0000] {logging_mixin.py:188} INFO - 35182380619
[2024-06-26T07:20:41.140+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/url HTTP/1.1" 200 0
[2024-06-26T07:20:41.173+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/element HTTP/1.1" 200 0
[2024-06-26T07:20:41.210+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "GET /session/f2094bc7b0d0951fb3e816ef9ed97482/element/f.BCC00DE3CA51A86ADAAF72288542F68A.d.90D6F4183D16F2864E3B295143B79DC6.e.4/text HTTP/1.1" 200 0
[2024-06-26T07:20:41.213+0000] {logging_mixin.py:188} INFO - ok
[2024-06-26T07:20:44.752+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/url HTTP/1.1" 200 0
[2024-06-26T07:20:44.773+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/element HTTP/1.1" 200 0
[2024-06-26T07:20:45.010+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "GET /session/f2094bc7b0d0951fb3e816ef9ed97482/element/f.BCC00DE3CA51A86ADAAF72288542F68A.d.0B251E7CA59B07E94E01A67D631681A7.e.6/text HTTP/1.1" 200 0
[2024-06-26T07:20:52.006+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/url HTTP/1.1" 200 0
[2024-06-26T07:20:52.338+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/element HTTP/1.1" 200 0
[2024-06-26T07:20:53.390+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "GET /session/f2094bc7b0d0951fb3e816ef9ed97482/element/f.BCC00DE3CA51A86ADAAF72288542F68A.d.F89ADAEA1A110740846564B53749CEE1.e.8/text HTTP/1.1" 200 0
[2024-06-26T07:20:53.433+0000] {fun_page.py:109} INFO - getting another set
[2024-06-26T07:20:59.435+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/url HTTP/1.1" 200 0
[2024-06-26T07:20:59.493+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/element HTTP/1.1" 200 0
[2024-06-26T07:20:59.881+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "GET /session/f2094bc7b0d0951fb3e816ef9ed97482/element/f.BCC00DE3CA51A86ADAAF72288542F68A.d.FA70C33168CADF7FE3078B703E67A2DF.e.10/text HTTP/1.1" 200 0
[2024-06-26T07:20:59.913+0000] {fun_page.py:109} INFO - getting another set
[2024-06-26T07:21:06.611+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/url HTTP/1.1" 200 0
[2024-06-26T07:21:06.635+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/element HTTP/1.1" 200 0
[2024-06-26T07:21:07.102+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "GET /session/f2094bc7b0d0951fb3e816ef9ed97482/element/f.BCC00DE3CA51A86ADAAF72288542F68A.d.564955B2C9BB2192492248741441617C.e.12/text HTTP/1.1" 200 0
[2024-06-26T07:21:07.170+0000] {fun_page.py:109} INFO - getting another set
[2024-06-26T07:21:11.391+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/url HTTP/1.1" 200 0
[2024-06-26T07:21:11.420+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/element HTTP/1.1" 200 0
[2024-06-26T07:21:11.665+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "GET /session/f2094bc7b0d0951fb3e816ef9ed97482/element/f.BCC00DE3CA51A86ADAAF72288542F68A.d.1BEC48F37EFD25EC0456C5AB728B7BD5.e.14/text HTTP/1.1" 200 0
[2024-06-26T07:21:11.684+0000] {fun_page.py:109} INFO - getting another set
[2024-06-26T07:21:17.825+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/url HTTP/1.1" 200 0
[2024-06-26T07:21:17.846+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/element HTTP/1.1" 200 0
[2024-06-26T07:21:18.103+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "GET /session/f2094bc7b0d0951fb3e816ef9ed97482/element/f.BCC00DE3CA51A86ADAAF72288542F68A.d.36332996E747AF4A1FFFDE2426E1FD24.e.16/text HTTP/1.1" 200 0
[2024-06-26T07:21:18.127+0000] {fun_page.py:109} INFO - getting another set
[2024-06-26T07:21:25.740+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/url HTTP/1.1" 200 0
[2024-06-26T07:21:25.810+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/element HTTP/1.1" 200 0
[2024-06-26T07:21:26.171+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "GET /session/f2094bc7b0d0951fb3e816ef9ed97482/element/f.BCC00DE3CA51A86ADAAF72288542F68A.d.33C46529272B3D815A9D3FB332986422.e.18/text HTTP/1.1" 200 0
[2024-06-26T07:21:26.194+0000] {fun_page.py:109} INFO - getting another set
[2024-06-26T07:22:04.378+0000] {job.py:218} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 192, in heartbeat
    self._merge_from(Job._fetch_from_db(self, session))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/retries.py", line 89, in wrapped_function
    for attempt in run_with_db_retries(max_retries=retries, logger=logger, **retry_kwargs):
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 435, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 368, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 410, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 183, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/retries.py", line 98, in wrapped_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 316, in _fetch_from_db
    session.merge(job)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-06-26T07:22:09.278+0000] {job.py:226} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-06-26T07:23:13.114+0000] {job.py:226} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-06-26T07:25:19.835+0000] {job.py:226} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-06-26T07:25:27.616+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/url HTTP/1.1" 200 0
[2024-06-26T07:25:37.169+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/element HTTP/1.1" 200 0
[2024-06-26T07:25:39.336+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "GET /session/f2094bc7b0d0951fb3e816ef9ed97482/element/f.BCC00DE3CA51A86ADAAF72288542F68A.d.3BC4A4F5A0C61FF315B50DCC7C798A2F.e.20/text HTTP/1.1" 200 0
[2024-06-26T07:25:40.074+0000] {fun_page.py:109} INFO - getting another set
[2024-06-26T07:25:52.039+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/url HTTP/1.1" 200 0
[2024-06-26T07:25:52.167+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/element HTTP/1.1" 200 0
[2024-06-26T07:25:53.018+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "GET /session/f2094bc7b0d0951fb3e816ef9ed97482/element/f.BCC00DE3CA51A86ADAAF72288542F68A.d.B1331C5B61D9D08238FD39836B37F980.e.22/text HTTP/1.1" 200 0
[2024-06-26T07:25:53.067+0000] {fun_page.py:109} INFO - getting another set
[2024-06-26T07:25:58.720+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/url HTTP/1.1" 200 0
[2024-06-26T07:25:58.787+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/element HTTP/1.1" 200 0
[2024-06-26T07:25:59.911+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "GET /session/f2094bc7b0d0951fb3e816ef9ed97482/element/f.BCC00DE3CA51A86ADAAF72288542F68A.d.A20D8E3C7E9FE4DCC91AB97060E2889E.e.24/text HTTP/1.1" 200 0
[2024-06-26T07:26:00.041+0000] {fun_page.py:109} INFO - getting another set
[2024-06-26T07:26:11.143+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/url HTTP/1.1" 200 0
[2024-06-26T07:26:11.181+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/element HTTP/1.1" 200 0
[2024-06-26T07:26:11.524+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "GET /session/f2094bc7b0d0951fb3e816ef9ed97482/element/f.BCC00DE3CA51A86ADAAF72288542F68A.d.B457E633E1F310391C4F2B9D834449E3.e.26/text HTTP/1.1" 200 0
[2024-06-26T07:26:11.546+0000] {fun_page.py:109} INFO - getting another set
[2024-06-26T07:26:16.840+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/url HTTP/1.1" 200 0
[2024-06-26T07:26:16.870+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/element HTTP/1.1" 200 0
[2024-06-26T07:26:17.142+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "GET /session/f2094bc7b0d0951fb3e816ef9ed97482/element/f.BCC00DE3CA51A86ADAAF72288542F68A.d.37A2A2E2C228366A542DAD645BC06A71.e.28/text HTTP/1.1" 200 0
[2024-06-26T07:26:17.161+0000] {fun_page.py:109} INFO - getting another set
[2024-06-26T07:26:22.230+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/url HTTP/1.1" 200 0
[2024-06-26T07:26:22.252+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/element HTTP/1.1" 200 0
[2024-06-26T07:26:22.494+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "GET /session/f2094bc7b0d0951fb3e816ef9ed97482/element/f.BCC00DE3CA51A86ADAAF72288542F68A.d.1F28D35C7BB1E62D05D57AEE57EC5ECF.e.30/text HTTP/1.1" 200 0
[2024-06-26T07:26:22.526+0000] {fun_page.py:109} INFO - getting another set
[2024-06-26T07:26:27.305+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/url HTTP/1.1" 200 0
[2024-06-26T07:26:27.327+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/element HTTP/1.1" 200 0
[2024-06-26T07:26:27.717+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "GET /session/f2094bc7b0d0951fb3e816ef9ed97482/element/f.BCC00DE3CA51A86ADAAF72288542F68A.d.A51C6C439318636E53D2F11CBEA7859A.e.32/text HTTP/1.1" 200 0
[2024-06-26T07:26:27.736+0000] {fun_page.py:109} INFO - getting another set
[2024-06-26T07:26:36.981+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/url HTTP/1.1" 200 0
[2024-06-26T07:26:37.002+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/element HTTP/1.1" 200 0
[2024-06-26T07:26:37.436+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "GET /session/f2094bc7b0d0951fb3e816ef9ed97482/element/f.BCC00DE3CA51A86ADAAF72288542F68A.d.9BE4A973F58CA5729E5537A6E2C2EB78.e.34/text HTTP/1.1" 200 0
[2024-06-26T07:26:37.500+0000] {fun_page.py:109} INFO - getting another set
[2024-06-26T07:26:48.579+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/url HTTP/1.1" 200 0
[2024-06-26T07:26:48.603+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/element HTTP/1.1" 200 0
[2024-06-26T07:26:48.998+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "GET /session/f2094bc7b0d0951fb3e816ef9ed97482/element/f.BCC00DE3CA51A86ADAAF72288542F68A.d.235169ED70A736EFE767C7E2602A2020.e.36/text HTTP/1.1" 200 0
[2024-06-26T07:26:49.022+0000] {fun_page.py:109} INFO - getting another set
[2024-06-26T07:26:56.411+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/url HTTP/1.1" 200 0
[2024-06-26T07:26:56.585+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/element HTTP/1.1" 200 0
[2024-06-26T07:26:57.036+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "GET /session/f2094bc7b0d0951fb3e816ef9ed97482/element/f.BCC00DE3CA51A86ADAAF72288542F68A.d.74786AEBB26E168A95470BE03EDAAFE0.e.38/text HTTP/1.1" 200 0
[2024-06-26T07:26:57.058+0000] {fun_page.py:109} INFO - getting another set
[2024-06-26T07:27:02.759+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/url HTTP/1.1" 200 0
[2024-06-26T07:27:02.829+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/element HTTP/1.1" 200 0
[2024-06-26T07:27:03.111+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "GET /session/f2094bc7b0d0951fb3e816ef9ed97482/element/f.BCC00DE3CA51A86ADAAF72288542F68A.d.C19CBB70540A93E57BE5BB33ABB0E084.e.40/text HTTP/1.1" 200 0
[2024-06-26T07:27:03.157+0000] {fun_page.py:109} INFO - getting another set
[2024-06-26T07:27:08.581+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/url HTTP/1.1" 200 0
[2024-06-26T07:27:08.653+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/element HTTP/1.1" 200 0
[2024-06-26T07:27:09.326+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "GET /session/f2094bc7b0d0951fb3e816ef9ed97482/element/f.BCC00DE3CA51A86ADAAF72288542F68A.d.20056D7B77FAB8ACA2BE555FC92D890E.e.42/text HTTP/1.1" 200 0
[2024-06-26T07:27:09.349+0000] {fun_page.py:109} INFO - getting another set
[2024-06-26T07:27:15.378+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/url HTTP/1.1" 200 0
[2024-06-26T07:27:15.438+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/element HTTP/1.1" 200 0
[2024-06-26T07:27:15.779+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "GET /session/f2094bc7b0d0951fb3e816ef9ed97482/element/f.BCC00DE3CA51A86ADAAF72288542F68A.d.F198466AE01A33067448D4EEEAABE4DD.e.44/text HTTP/1.1" 200 0
[2024-06-26T07:27:15.831+0000] {fun_page.py:109} INFO - getting another set
[2024-06-26T07:27:21.457+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/url HTTP/1.1" 200 0
[2024-06-26T07:27:21.471+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/element HTTP/1.1" 200 0
[2024-06-26T07:27:21.707+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "GET /session/f2094bc7b0d0951fb3e816ef9ed97482/element/f.BCC00DE3CA51A86ADAAF72288542F68A.d.33DF93612F03F6C4DC6F67F4C9B7A2C6.e.46/text HTTP/1.1" 200 0
[2024-06-26T07:27:21.727+0000] {fun_page.py:109} INFO - getting another set
[2024-06-26T07:27:28.503+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/url HTTP/1.1" 200 0
[2024-06-26T07:27:28.522+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/element HTTP/1.1" 200 0
[2024-06-26T07:27:28.764+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "GET /session/f2094bc7b0d0951fb3e816ef9ed97482/element/f.BCC00DE3CA51A86ADAAF72288542F68A.d.902C89020AF3F105EBD53DEA5D816FB0.e.48/text HTTP/1.1" 200 0
[2024-06-26T07:27:28.786+0000] {fun_page.py:109} INFO - getting another set
[2024-06-26T07:28:14.315+0000] {job.py:226} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-06-26T07:28:49.057+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "POST /session/f2094bc7b0d0951fb3e816ef9ed97482/url HTTP/1.1" 500 0
[2024-06-26T07:28:49.364+0000] {connectionpool.py:549} DEBUG - http://localhost:51561 "DELETE /session/f2094bc7b0d0951fb3e816ef9ed97482 HTTP/1.1" 200 0
[2024-06-26T07:28:50.085+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-26T07:28:50.133+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/page_airflow.py", line 126, in process_link
    result = run_selenium_job(link)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/page_airflow.py", line 68, in run_selenium_job
    result = functions_instance.get_all_data(driver, page_id, access_token)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fun/fun_page.py", line 246, in get_all_data
    posts_dict = self.get_posts(driver, user_id, access_token)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fun/fun_page.py", line 94, in get_posts
    driver.get(next_url)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome-headless-shell=126.0.6478.114)
Stacktrace:
#0 0x5607f16658ae <unknown>
#1 0x5607f1336966 <unknown>
#2 0x5607f1323899 <unknown>
#3 0x5607f1322fa6 <unknown>
#4 0x5607f132284b <unknown>
#5 0x5607f13226e0 <unknown>
#6 0x5607f1320ba0 <unknown>
#7 0x5607f13210b9 <unknown>
#8 0x5607f132ea14 <unknown>
#9 0x5607f1341f6f <unknown>
#10 0x5607f134668b <unknown>
#11 0x5607f132165b <unknown>
#12 0x5607f1341b71 <unknown>
#13 0x5607f13bdb22 <unknown>
#14 0x5607f13a0893 <unknown>
#15 0x5607f13712ed <unknown>
#16 0x5607f1372092 <unknown>
#17 0x5607f1635256 <unknown>
#18 0x5607f16385f9 <unknown>
#19 0x5607f16380bf <unknown>
#20 0x5607f1638a75 <unknown>
#21 0x5607f162579f <unknown>
#22 0x5607f1638dc0 <unknown>
#23 0x5607f160e6c6 <unknown>
#24 0x5607f1655fb5 <unknown>
#25 0x5607f16561a2 <unknown>
#26 0x5607f1664d9a <unknown>
#27 0x7f557d13f134 <unknown>

[2024-06-26T07:28:50.523+0000] {taskinstance.py:562} DEBUG - Task Duration set to 494.084078
[2024-06-26T07:28:50.676+0000] {taskinstance.py:584} DEBUG - Clearing next_method and next_kwargs.
[2024-06-26T07:28:50.684+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=PAGE1, task_id=process_link_0, run_id=manual__2024-06-26T07:20:29.160351+00:00, execution_date=20240626T072029, start_date=20240626T072036, end_date=20240626T072850
[2024-06-26T07:28:50.978+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 526 for task process_link_0 (Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome-headless-shell=126.0.6478.114)
Stacktrace:
#0 0x5607f16658ae <unknown>
#1 0x5607f1336966 <unknown>
#2 0x5607f1323899 <unknown>
#3 0x5607f1322fa6 <unknown>
#4 0x5607f132284b <unknown>
#5 0x5607f13226e0 <unknown>
#6 0x5607f1320ba0 <unknown>
#7 0x5607f13210b9 <unknown>
#8 0x5607f132ea14 <unknown>
#9 0x5607f1341f6f <unknown>
#10 0x5607f134668b <unknown>
#11 0x5607f132165b <unknown>
#12 0x5607f1341b71 <unknown>
#13 0x5607f13bdb22 <unknown>
#14 0x5607f13a0893 <unknown>
#15 0x5607f13712ed <unknown>
#16 0x5607f1372092 <unknown>
#17 0x5607f1635256 <unknown>
#18 0x5607f16385f9 <unknown>
#19 0x5607f16380bf <unknown>
#20 0x5607f1638a75 <unknown>
#21 0x5607f162579f <unknown>
#22 0x5607f1638dc0 <unknown>
#23 0x5607f160e6c6 <unknown>
#24 0x5607f1655fb5 <unknown>
#25 0x5607f16561a2 <unknown>
#26 0x5607f1664d9a <unknown>
#27 0x7f557d13f134 <unknown>
; 1505)
[2024-06-26T07:28:51.097+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-26T07:28:51.439+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-26T07:28:51.445+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
